linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: unused-parameter
        disabled: true

issues:
  exclude-use-default: false
  # Ігноруємо конкретні типи помилок
  exclude-rules:
    - linters: [errcheck]
      text: "Error return value of .*(Rollback|Close|Sscanf|Start|Stop).* is not checked"
    - linters: [unused]
      text: "type `outboxMsg` is unused"
    - linters: [misspell]
      text: "substract"
    - linters: [ineffassign]
      path: pkg/storage/workout.go

run:
  timeout: 5m
