services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    env_file:
      - .env
    extra_hosts:
      - "api.telegram.org:149.154.167.220"
    # Ми прибираємо перевизначення DATABASE_URL, щоб він брався безпосередньо з .env
    # А також прибираємо залежність від локальної бази db
